dbt_usage_events:
  target: dev
  outputs:
    dev:
      type: glue
      query-comment: demo-raw_events
      role_arn: "{{ env_var('DBT_ROLE_ARN') }}"
      region: us-east-1
      workers: 5
      worker_type: G.1X
      schema: "dbt_raw_events"
      database: "dbt_raw_events"
      session_provisioning_timeout_in_seconds: 120
      location: "{{ env_var('DBT_S3_LOCATION') }}"
